version: 2.1

defaults: &defaults
    docker:
      - image: cimg/node:20.8.1
    working_directory: ~/repo

commands:
  install_dependencies:
    description: "Install and cache dependencies"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install --omit=dev
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build_and_push_docker:
    description: "Build and push Docker image with GitHub tag"
    steps:
      - setup_remote_docker
      - run:
          name: "Build Docker image"
          command: |
            docker build -t $DOCKERHUB_USERNAME/destygo-chat-performance-test:$CIRCLE_TAG .
            docker build -t $DOCKERHUB_USERNAME/destygo-chat-performance-test:latest .
      - run:
          name: "Push Docker images"
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/destygo-chat-performance-test:$CIRCLE_TAG
            docker push $DOCKERHUB_USERNAME/destygo-chat-performance-test:latest

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - install_dependencies

  docker:
    <<: *defaults
    steps:
      - checkout
      - install_dependencies
      - build_and_push_docker

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
  docker_release:
    jobs:
      - docker:
          filters:
            tags:
              only: /^v.*/
