version: 2.1

defaults: &defaults
    docker:
      - image: cimg/node:18.0.0
    working_directory: ~/repo

commands:
  install_dependencies:
    description: "Install and cache dependencies"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm ci --production=false
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - install_dependencies
      - run:
          name: "Run connection test"
          command: npm run test:connection:quick
          no_output_timeout: 5m

  release:
    <<: *defaults
    steps:
      - checkout
      - install_dependencies
      - setup_remote_docker
      - run:
          name: "Setup Git"
          command: |
            git config --global user.email "ci@viasay.io"
            git config --global user.name "CircleCI"
      - run:
          name: "Run Semantic Release"
          command: npx semantic-release
          environment:
            GITHUB_TOKEN: $GITHUB_TOKEN
            DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
            DOCKERHUB_PASS: $DOCKERHUB_PASS

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
